# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
<<<<<<< HEAD
          name: 'echo an env var that is part of the project'
          command:
            echo CI_TRY
=======
          name: "echo an env var that is part of the project"
          command:
            echo $CI_TRY
>>>>>>> eb998d2ce1485b859255ba5ce92e0b05402f5568


